# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20170829_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vale',
            name='no_folio',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
