# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20170904_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vale',
            name='material',
            field=models.ManyToManyField(to='inventario.DetalleMaterial'),
        ),
    ]
