# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
