# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('grado', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=20)),
                ('cp', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('notas', models.CharField(max_length=50)),
                ('catecismo', models.CharField(max_length=10)),
                ('serviciomedico', models.CharField(max_length=25)),
                ('sangre', models.CharField(max_length=4)),
                ('alergias', models.CharField(max_length=30)),
                ('enfermedadcronica', models.CharField(max_length=30)),
                ('nombrepadre', models.CharField(max_length=30)),
                ('ocupacionpadre', models.CharField(max_length=20)),
                ('trabajopadre', models.CharField(max_length=20)),
                ('telpadre', models.IntegerField()),
                ('celpadre', models.IntegerField()),
                ('nombremadre', models.CharField(max_length=30)),
                ('ocupacionmadre', models.CharField(max_length=20)),
                ('trabajomadre', models.CharField(max_length=20)),
                ('telmadre', models.IntegerField()),
                ('celmadre', models.IntegerField()),
                ('nombreautorizada', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=15)),
                ('ocupacionaut', models.CharField(max_length=20)),
                ('trabajoaut', models.CharField(max_length=20)),
                ('telaut', models.IntegerField()),
                ('celaut', models.IntegerField()),
            ],
        ),
    ]
