# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='celaut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celmadre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celpadre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='cp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telaut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telmadre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telpadre',
            field=models.CharField(max_length=10),
        ),
    ]
