# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20170717_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='notas',
            field=models.TextField(max_length=100),
        ),
    ]
