# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20170717_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='escolaridad_alum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Escolaridad'),
        ),
    ]
