# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20170719_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='alergias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='catecismo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celaut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celmadre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celpadre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='enfermedadcronica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='escolaridad_alum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Escolaridad'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombreautorizada',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombremadre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombrepadre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='notas',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='ocupacionaut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='ocupacionmadre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='ocupacionpadre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='parentesco',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='serviciomedico',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telaut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telmadre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telpadre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='trabajoaut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='trabajomadre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='trabajopadre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
