# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_auto_20170719_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sexo_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.SexoModel'),
        ),
    ]
