# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20170720_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='edad',
        ),
    ]
