# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_remove_datospersonales_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/foto'),
        ),
    ]
