# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_datospersonales_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
