# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='papelestrasa_metro',
            new_name='papeles_trasa_metro',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='paquete_papelsanitario',
            new_name='paquete_papel_sanitario',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='paquete_toallasdepapel',
            new_name='paquete_toallas_papel',
        ),
    ]
