# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_auto_20170726_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='alumno_inv',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='caja_conos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='caja_pañuelos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='candado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='papel_china',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='papel_crepe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='papelbond_colores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='papeles_trasa_metro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='paquete_500hojas_blanca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='paquete_papel_sanitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='paquete_toallas_papel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='rotafolio_blanco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='rotafolio_cuadrado',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
