# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_generacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='img/fotos/egresados')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresados.Generacion')),
            ],
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mencion_honorifica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel_escolar', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='listado',
            name='mencion_honorifica',
            field=models.ManyToManyField(to='egresados.Mencion'),
        ),
        migrations.AddField(
            model_name='listado',
            name='nivel_escolar',
            field=models.ManyToManyField(to='egresados.NivelEscolar'),
        ),
    ]
