# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listado',
            name='nivel_escolar',
        ),
        migrations.AddField(
            model_name='listado',
            name='nivel_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='egresados.NivelEscolar'),
        ),
    ]
