# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0002_auto_20170725_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='foto',
            field=models.ImageField(null=True, upload_to='img/fotos/egresados'),
        ),
        migrations.AlterField(
            model_name='listado',
            name='mencion_honorifica',
            field=models.ManyToManyField(null=True, to='egresados.Mencion'),
        ),
    ]
