# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0003_auto_20170725_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listado',
            name='mencion_honorifica',
        ),
        migrations.AddField(
            model_name='listado',
            name='mencion_honorifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='egresados.Mencion'),
        ),
    ]
