# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto6', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto7', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto8', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto9', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto10', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto11', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto12', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto13', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto14', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto15', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto16', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto17', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto18', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto19', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto20', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto21', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto22', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto23', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto24', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
                ('foto25', models.ImageField(blank=True, null=True, upload_to='img/evento/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
