# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20170727_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='foto26',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='foto27',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='foto28',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto10',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto11',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto12',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto13',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto14',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto15',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto16',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto17',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto18',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto19',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto20',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto21',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto22',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto23',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto24',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto25',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto6',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto7',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto8',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto9',
            field=models.ImageField(blank=True, null=True, upload_to='img/evento/'),
        ),
    ]
